package dao;

import model.Address;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * AddressDAO.java
 * CSc3350 Team Project SP2026 — Team DataForge
 * Author: Banhi
 *
 * Data Access Object for the addresses table.
 * Handles all database operations for addresses:
 * add, update, get by ID.
 *
 * All methods use PreparedStatements for security.
 * All methods use DBConnection.getConnection() for the DB connection.
 */
public class AddressDAO {

    // ─── ADD ──────────────────────────────────────────────────────────────────

    /**
     * Inserts a new address into the addresses table.
     * addressID is AUTO_INCREMENT so it is generated by the DB.
     *
     * @param a Address object with all fields set (no addressID needed)
     * @return the generated addressID if successful, -1 if failed
     */
    public int addAddress(Address a) {
        String sql = "INSERT INTO addresses (street, cityID, stateID, zip, DOB, phone, " +
                     "emergency_contact_name, emergency_contact_phone) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
        try {
            Connection conn = DBConnection.getConnection();
            PreparedStatement ps = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
            ps.setString(1, a.getStreet());
            ps.setInt(2, a.getCityID());
            ps.setInt(3, a.getStateID());
            ps.setString(4, a.getZip());
            ps.setString(5, a.getDob());
            ps.setString(6, a.getPhone());
            ps.setString(7, a.getEmergencyContactName());
            ps.setString(8, a.getEmergencyContactPhone());

            int rows = ps.executeUpdate();

            if (rows > 0) {
                ResultSet keys = ps.getGeneratedKeys();
                if (keys.next()) {
                    int generatedID = keys.getInt(1);
                    keys.close();
                    ps.close();
                    System.out.println("  Address added successfully. Address ID: " + generatedID);
                    return generatedID;
                }
            }

            ps.close();
            System.out.println("  ERROR: Address could not be added.");
            return -1;

        } catch (SQLException ex) {
            System.out.println("  ERROR adding address: " + ex.getMessage());
            return -1;
        }
    }

    // ─── UPDATE ───────────────────────────────────────────────────────────────

    /**
     * Updates an existing address record in the database.
     * Uses the addressID field to identify which record to update.
     *
     * @param a Address object with updated field values
     * @return true if update was successful, false if it failed
     */
    public boolean updateAddress(Address a) {
        String sql = "UPDATE addresses SET street=?, cityID=?, stateID=?, zip=?, DOB=?, " +
                     "phone=?, emergency_contact_name=?, emergency_contact_phone=? " +
                     "WHERE addressID=?";
        try {
            Connection conn = DBConnection.getConnection();
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, a.getStreet());
            ps.setInt(2, a.getCityID());
            ps.setInt(3, a.getStateID());
            ps.setString(4, a.getZip());
            ps.setString(5, a.getDob());
            ps.setString(6, a.getPhone());
            ps.setString(7, a.getEmergencyContactName());
            ps.setString(8, a.getEmergencyContactPhone());
            ps.setInt(9, a.getAddressID());

            int rows = ps.executeUpdate();
            ps.close();

            if (rows > 0) {
                System.out.println("  Address updated successfully.");
                return true;
            } else {
                System.out.println("  ERROR: No address found with ID: " + a.getAddressID());
                return false;
            }

        } catch (SQLException ex) {
            System.out.println("  ERROR updating address: " + ex.getMessage());
            return false;
        }
    }

    // ─── GET ──────────────────────────────────────────────────────────────────

    /**
     * Retrieves an address record by its addressID.
     *
     * @param id the addressID to search for
     * @return Address object if found, null if not found
     */
    public Address getAddressByID(int id) {
        String sql = "SELECT * FROM addresses WHERE addressID = ?";
        try {
            Connection conn = DBConnection.getConnection();
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, id);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                Address a = mapResultSet(rs);
                rs.close();
                ps.close();
                return a;
            } else {
                System.out.println("  No address found with ID: " + id);
                rs.close();
                ps.close();
                return null;
            }

        } catch (SQLException ex) {
            System.out.println("  ERROR retrieving address: " + ex.getMessage());
            return null;
        }
    }

    // ─── HELPER ───────────────────────────────────────────────────────────────

    /**
     * Maps a ResultSet row to an Address object.
     * Used internally by search methods.
     *
     * @param rs ResultSet positioned at the row to map
     * @return Address object with all fields populated
     */
    private Address mapResultSet(ResultSet rs) throws SQLException {
        return new Address(
            rs.getInt("addressID"),
            rs.getString("street"),
            rs.getInt("cityID"),
            rs.getInt("stateID"),
            rs.getString("zip"),
            rs.getString("DOB"),
            rs.getString("phone"),
            rs.getString("emergency_contact_name"),
            rs.getString("emergency_contact_phone")
        );
    }
}
